services:
  - type: web
    name: churn-prediction-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        generateValue: false
        value: 8080
